// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "flscreen.h"

Fl_Tabs *tabs_window=(Fl_Tabs *)0;

Fl_Group *tab_device_infomation=(Fl_Group *)0;

Fl_Round_Button *radio_single_pulse=(Fl_Round_Button *)0;

Fl_Round_Button *radio_twin_pulse=(Fl_Round_Button *)0;

Fl_Int_Input *sys_pickup_degree=(Fl_Int_Input *)0;

MyMsg *msg=(MyMsg *)0;

Fl_Output *dev_manufacture=(Fl_Output *)0;

Fl_Output *dev_product=(Fl_Output *)0;

Fl_Output *dev_mapsw=(Fl_Output *)0;

Fl_Output *dev_quickshifter=(Fl_Output *)0;

Fl_Output *dev_rpm=(Fl_Output *)0;

Fl_Output *dev_pv_pot=(Fl_Output *)0;

Fl_Output *dev_devid=(Fl_Output *)0;

Fl_Output *dev_revid=(Fl_Output *)0;

Fl_Output *dev_pv_target=(Fl_Output *)0;

Fl_Output *dev_pv_mode=(Fl_Output *)0;

Fl_Output *dev_pv_mt_state=(Fl_Output *)0;

Fl_Button *btn_dev_read=(Fl_Button *)0;

Fl_Button *btn_dev_write=(Fl_Button *)0;

Fl_Button *btn_file_open=(Fl_Button *)0;

Fl_Button *btn_file_save=(Fl_Button *)0;

Fl_Output *dev_th_pot=(Fl_Output *)0;

Fl_Progress *pr_cputemp_current=(Fl_Progress *)0;

Fl_Group *tab_map_settings=(Fl_Group *)0;

MyChart *chart_ign=(MyChart *)0;

MyChart *chart_pvs=(MyChart *)0;

Fl_Repeat_Button *btn_map_up=(Fl_Repeat_Button *)0;

Fl_Repeat_Button *btn_map_down=(Fl_Repeat_Button *)0;

Fl_Repeat_Button *btn_map_left=(Fl_Repeat_Button *)0;

Fl_Repeat_Button *btn_map_right=(Fl_Repeat_Button *)0;

Fl_Light_Button *btn_select_ign_map0=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_ign_map1=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_ign_map2=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_ign_map3=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_pvs_map0=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_pvs_map1=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_pvs_map2=(Fl_Light_Button *)0;

Fl_Light_Button *btn_select_pvs_map3=(Fl_Light_Button *)0;

Fl_Round_Button *radio_map_x1=(Fl_Round_Button *)0;

Fl_Round_Button *radio_map_x5=(Fl_Round_Button *)0;

Fl_Round_Button *radio_map_x10=(Fl_Round_Button *)0;

Fl_Group *tab_quick_shifter=(Fl_Group *)0;

Fl_Value_Slider *vs_qs_enable_rpm=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_qs_sw_on_count=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_qs_cut_count=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_qs_disable_count=(Fl_Value_Slider *)0;

Fl_Light_Button *btn_qs_reverse_onoff_state=(Fl_Light_Button *)0;

Fl_Light_Button *btn_qs_use_as_stopsw=(Fl_Light_Button *)0;

Fl_Group *tab_option_settings=(Fl_Group *)0;

Fl_Value_Slider *vs_rev_limit=(Fl_Value_Slider *)0;

Fl_Round_Button *radio_optc2_pulse_out=(Fl_Round_Button *)0;

Fl_Round_Button *radio_optc2_map_out=(Fl_Round_Button *)0;

Fl_Round_Button *radio_opt_mapsw_type1=(Fl_Round_Button *)0;

Fl_Round_Button *radio_opt_mapsw_type2=(Fl_Round_Button *)0;

Fl_Round_Button *radio_opt_mapsw_type4=(Fl_Round_Button *)0;

Fl_Value_Slider *vs_count_of_an_ignition=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_rpm_for_an_ignition=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_throttle_1to2=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_throttle_2to3=(Fl_Value_Slider *)0;

Fl_Value_Slider *vs_throttle_3to4=(Fl_Value_Slider *)0;

Fl_Progress *pr_tp_current=(Fl_Progress *)0;

Fl_Round_Button *radio_opt_pv_init_open_end=(Fl_Round_Button *)0;

Fl_Round_Button *radio_opt_pv_init_close_end=(Fl_Round_Button *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1280, 720);
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)55);
    { tabs_window = new Fl_Tabs(0, 0, 1280, 720);
      tabs_window->color((Fl_Color)23);
      tabs_window->labeltype(FL_NO_LABEL);
      tabs_window->labelsize(18);
      { tab_device_infomation = new Fl_Group(0, 60, 1280, 660, "    &Device Infomation");
        tab_device_infomation->labelsize(20);
        tab_device_infomation->hide();
        { Fl_Box* o = new Fl_Box(60, 301, 550, 179, "Input Signal Status");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(60, 100, 550, 170, "Production name");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(60, 511, 550, 179, "Power Valve Motor Status");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Box* o
        { Fl_Group* o = new Fl_Group(650, 100, 580, 130, "Engine Type Settings");
          o->box(FL_BORDER_FRAME);
          o->color(FL_FOREGROUND_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { radio_single_pulse = new Fl_Round_Button(660, 109, 209, 30, "1 pulse in one rotation");
            radio_single_pulse->type(102);
            radio_single_pulse->down_box(FL_ROUND_DOWN_BOX);
            radio_single_pulse->labelsize(24);
            radio_single_pulse->callback((Fl_Callback*)cb_engine_type);
          } // Fl_Round_Button* radio_single_pulse
          { radio_twin_pulse = new Fl_Round_Button(930, 109, 209, 30, "2 pulse in one rotation");
            radio_twin_pulse->type(102);
            radio_twin_pulse->down_box(FL_ROUND_DOWN_BOX);
            radio_twin_pulse->value(1);
            radio_twin_pulse->labelsize(24);
            radio_twin_pulse->callback((Fl_Callback*)cb_engine_type);
          } // Fl_Round_Button* radio_twin_pulse
          { Fl_Box* o = new Fl_Box(650, 152, 560, 18, "NOTE:Crank case lead type must change pick up coil position by yourself.");
            o->labelsize(16);
          } // Fl_Box* o
          { sys_pickup_degree = new Fl_Int_Input(1120, 185, 60, 33, "Pick up coil position");
            sys_pickup_degree->type(2);
            sys_pickup_degree->labelsize(24);
            sys_pickup_degree->textsize(18);
            sys_pickup_degree->callback((Fl_Callback*)cb_sys_pickup_degree);
          } // Fl_Int_Input* sys_pickup_degree
          o->end();
        } // Fl_Group* o
        { msg = new MyMsg(650, 331, 580, 299, "Log:");
          msg->type(12);
          msg->box(FL_DOWN_BOX);
          msg->color(FL_FOREGROUND_COLOR);
          msg->selection_color(FL_SELECTION_COLOR);
          msg->labeltype(FL_NORMAL_LABEL);
          msg->labelfont(0);
          msg->labelsize(18);
          msg->labelcolor(FL_FOREGROUND_COLOR);
          msg->textfont(13);
          msg->textsize(18);
          msg->textcolor(FL_BACKGROUND2_COLOR);
          msg->align(Fl_Align(133));
          msg->when(FL_WHEN_RELEASE);
        } // MyMsg* msg
        { dev_manufacture = new Fl_Output(186, 109, 382, 30, "Manufacture");
          dev_manufacture->color((Fl_Color)23);
          dev_manufacture->labelsize(18);
          dev_manufacture->textsize(18);
        } // Fl_Output* dev_manufacture
        { dev_product = new Fl_Output(186, 149, 382, 30, "Product");
          dev_product->color((Fl_Color)23);
          dev_product->labelsize(18);
          dev_product->textsize(18);
        } // Fl_Output* dev_product
        { dev_mapsw = new Fl_Output(370, 360, 200, 30, "Map switch");
          dev_mapsw->color((Fl_Color)23);
          dev_mapsw->labelsize(18);
          dev_mapsw->textsize(18);
        } // Fl_Output* dev_mapsw
        { dev_quickshifter = new Fl_Output(370, 440, 200, 30, "Quick shifter switch");
          dev_quickshifter->color((Fl_Color)23);
          dev_quickshifter->labelsize(18);
          dev_quickshifter->textsize(18);
        } // Fl_Output* dev_quickshifter
        { dev_rpm = new Fl_Output(370, 320, 200, 30, "R.P.M.");
          dev_rpm->color((Fl_Color)23);
          dev_rpm->labelsize(18);
          dev_rpm->textsize(18);
        } // Fl_Output* dev_rpm
        { dev_pv_pot = new Fl_Output(370, 570, 200, 30, "PV Current angle");
          dev_pv_pot->color((Fl_Color)23);
          dev_pv_pot->labelsize(18);
          dev_pv_pot->textsize(18);
        } // Fl_Output* dev_pv_pot
        { dev_devid = new Fl_Output(260, 227, 120, 33, "PIC DevID");
          dev_devid->color((Fl_Color)23);
          dev_devid->labelsize(18);
          dev_devid->textsize(18);
        } // Fl_Output* dev_devid
        { dev_revid = new Fl_Output(450, 227, 120, 33, "RevID");
          dev_revid->color((Fl_Color)23);
          dev_revid->labelsize(18);
          dev_revid->textsize(18);
        } // Fl_Output* dev_revid
        { dev_pv_target = new Fl_Output(370, 530, 200, 30, "PV Target");
          dev_pv_target->color((Fl_Color)23);
          dev_pv_target->labelsize(18);
          dev_pv_target->textsize(18);
        } // Fl_Output* dev_pv_target
        { dev_pv_mode = new Fl_Output(370, 650, 200, 30, "PV Mode");
          dev_pv_mode->color((Fl_Color)23);
          dev_pv_mode->labelsize(18);
          dev_pv_mode->textsize(18);
        } // Fl_Output* dev_pv_mode
        { dev_pv_mt_state = new Fl_Output(370, 610, 200, 30, "PV Motor state");
          dev_pv_mt_state->color((Fl_Color)23);
          dev_pv_mt_state->labelsize(18);
          dev_pv_mt_state->textsize(18);
        } // Fl_Output* dev_pv_mt_state
        { btn_dev_read = new Fl_Button(650, 240, 250, 60, "READ from device");
          btn_dev_read->color((Fl_Color)207);
          btn_dev_read->labelsize(18);
          btn_dev_read->callback((Fl_Callback*)cb_device_read);
        } // Fl_Button* btn_dev_read
        { btn_dev_write = new Fl_Button(980, 240, 250, 60, "WRITE to device");
          btn_dev_write->color((Fl_Color)254);
          btn_dev_write->labelsize(18);
          btn_dev_write->callback((Fl_Callback*)cb_device_write);
        } // Fl_Button* btn_dev_write
        { btn_file_open = new Fl_Button(650, 640, 250, 50, "File Open");
          btn_file_open->labelsize(18);
          btn_file_open->callback((Fl_Callback*)cb_file_open);
        } // Fl_Button* btn_file_open
        { btn_file_save = new Fl_Button(980, 640, 250, 50, "File Save");
          btn_file_save->labelsize(18);
          btn_file_save->callback((Fl_Callback*)cb_file_save);
        } // Fl_Button* btn_file_save
        { dev_th_pot = new Fl_Output(370, 400, 200, 30, "Map switch current");
          dev_th_pot->color((Fl_Color)23);
          dev_th_pot->labelsize(18);
          dev_th_pot->textsize(18);
        } // Fl_Output* dev_th_pot
        { pr_cputemp_current = new Fl_Progress(190, 192, 375, 25);
          pr_cputemp_current->selection_color(FL_DARK_GREEN);
        } // Fl_Progress* pr_cputemp_current
        tab_device_infomation->end();
      } // Fl_Group* tab_device_infomation
      { tab_map_settings = new Fl_Group(0, 60, 1280, 660, "&Map Settings        ");
        tab_map_settings->labelsize(20);
        tab_map_settings->hide();
        { chart_ign = new MyChart(180, 90, 800, 280, "Ignition");
          chart_ign->box(FL_UP_FRAME);
          chart_ign->color((Fl_Color)1);
          chart_ign->selection_color(FL_BACKGROUND_COLOR);
          chart_ign->labeltype(FL_NORMAL_LABEL);
          chart_ign->labelfont(0);
          chart_ign->labelsize(18);
          chart_ign->labelcolor(FL_FOREGROUND_COLOR);
          chart_ign->align(Fl_Align(FL_ALIGN_CENTER));
          chart_ign->when(FL_WHEN_RELEASE);
        } // MyChart* chart_ign
        { chart_pvs = new MyChart(180, 400, 800, 280, "pvs");
          chart_pvs->box(FL_UP_FRAME);
          chart_pvs->color((Fl_Color)1);
          chart_pvs->selection_color(FL_BACKGROUND_COLOR);
          chart_pvs->labeltype(FL_NORMAL_LABEL);
          chart_pvs->labelfont(0);
          chart_pvs->labelsize(18);
          chart_pvs->labelcolor(FL_FOREGROUND_COLOR);
          chart_pvs->align(Fl_Align(FL_ALIGN_CENTER));
          chart_pvs->when(FL_WHEN_RELEASE);
        } // MyChart* chart_pvs
        { btn_map_up = new Fl_Repeat_Button(1030, 180, 220, 130, "UP(&l)");
          btn_map_up->labelsize(24);
          btn_map_up->callback((Fl_Callback*)cb_up);
        } // Fl_Repeat_Button* btn_map_up
        { btn_map_down = new Fl_Repeat_Button(1030, 510, 220, 130, "DOWN(&k)");
          btn_map_down->labelsize(24);
          btn_map_down->callback((Fl_Callback*)cb_down);
        } // Fl_Repeat_Button* btn_map_down
        { btn_map_left = new Fl_Repeat_Button(1020, 320, 110, 180, "<<(&,)");
          btn_map_left->labelsize(24);
          btn_map_left->callback((Fl_Callback*)cb_left);
        } // Fl_Repeat_Button* btn_map_left
        { btn_map_right = new Fl_Repeat_Button(1150, 320, 110, 180, "(&.)>>");
          btn_map_right->labelsize(25);
          btn_map_right->callback((Fl_Callback*)cb_right);
        } // Fl_Repeat_Button* btn_map_right
        { btn_select_ign_map0 = new Fl_Light_Button(20, 90, 140, 60, "IGN MAP1(&1)");
          btn_select_ign_map0->type(102);
          btn_select_ign_map0->color((Fl_Color)252);
          btn_select_ign_map0->selection_color((Fl_Color)1);
          btn_select_ign_map0->labelsize(18);
          btn_select_ign_map0->callback((Fl_Callback*)cb_select_map);
          btn_select_ign_map0->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_ign_map0
        { btn_select_ign_map1 = new Fl_Light_Button(20, 160, 140, 60, "IGN MAP2(&2)");
          btn_select_ign_map1->type(102);
          btn_select_ign_map1->color((Fl_Color)246);
          btn_select_ign_map1->selection_color((Fl_Color)4);
          btn_select_ign_map1->labelsize(18);
          btn_select_ign_map1->callback((Fl_Callback*)cb_select_map);
          btn_select_ign_map1->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_ign_map1
        { btn_select_ign_map2 = new Fl_Light_Button(20, 230, 140, 60, "IGN MAP3(&3)");
          btn_select_ign_map2->type(102);
          btn_select_ign_map2->color(FL_YELLOW);
          btn_select_ign_map2->selection_color((Fl_Color)4);
          btn_select_ign_map2->labelsize(18);
          btn_select_ign_map2->callback((Fl_Callback*)cb_select_map);
          btn_select_ign_map2->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_ign_map2
        { btn_select_ign_map3 = new Fl_Light_Button(20, 300, 140, 60, "IGN MAP4(&4)");
          btn_select_ign_map3->type(102);
          btn_select_ign_map3->color((Fl_Color)87);
          btn_select_ign_map3->selection_color((Fl_Color)4);
          btn_select_ign_map3->labelsize(18);
          btn_select_ign_map3->callback((Fl_Callback*)cb_select_map);
          btn_select_ign_map3->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_ign_map3
        { btn_select_pvs_map0 = new Fl_Light_Button(20, 400, 140, 55, "PVS MAP1(&5)");
          btn_select_pvs_map0->type(102);
          btn_select_pvs_map0->color((Fl_Color)252);
          btn_select_pvs_map0->selection_color((Fl_Color)1);
          btn_select_pvs_map0->labelsize(18);
          btn_select_pvs_map0->callback((Fl_Callback*)cb_select_map);
          btn_select_pvs_map0->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_pvs_map0
        { btn_select_pvs_map1 = new Fl_Light_Button(20, 470, 140, 55, "PVS MAP2(&6)");
          btn_select_pvs_map1->type(102);
          btn_select_pvs_map1->color((Fl_Color)246);
          btn_select_pvs_map1->selection_color((Fl_Color)4);
          btn_select_pvs_map1->labelsize(18);
          btn_select_pvs_map1->callback((Fl_Callback*)cb_select_map);
          btn_select_pvs_map1->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_pvs_map1
        { btn_select_pvs_map2 = new Fl_Light_Button(20, 540, 140, 55, "PVS MAP3(&7)");
          btn_select_pvs_map2->type(102);
          btn_select_pvs_map2->color((Fl_Color)3);
          btn_select_pvs_map2->selection_color((Fl_Color)4);
          btn_select_pvs_map2->labelsize(18);
          btn_select_pvs_map2->callback((Fl_Callback*)cb_select_map);
          btn_select_pvs_map2->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_pvs_map2
        { btn_select_pvs_map3 = new Fl_Light_Button(20, 610, 140, 60, "PVS MAP4(&8)");
          btn_select_pvs_map3->type(102);
          btn_select_pvs_map3->color((Fl_Color)87);
          btn_select_pvs_map3->selection_color((Fl_Color)4);
          btn_select_pvs_map3->labelsize(18);
          btn_select_pvs_map3->callback((Fl_Callback*)cb_select_map);
          btn_select_pvs_map3->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* btn_select_pvs_map3
        { Fl_Group* o = new Fl_Group(1035, 130, 205, 40);
          { radio_map_x1 = new Fl_Round_Button(1035, 140, 25, 25, "x1");
            radio_map_x1->type(102);
            radio_map_x1->down_box(FL_ROUND_DOWN_BOX);
            radio_map_x1->value(1);
            radio_map_x1->labelsize(20);
          } // Fl_Round_Button* radio_map_x1
          { radio_map_x5 = new Fl_Round_Button(1100, 140, 25, 25, "x5");
            radio_map_x5->type(102);
            radio_map_x5->down_box(FL_ROUND_DOWN_BOX);
            radio_map_x5->labelsize(20);
          } // Fl_Round_Button* radio_map_x5
          { radio_map_x10 = new Fl_Round_Button(1160, 140, 25, 25, "x10");
            radio_map_x10->type(102);
            radio_map_x10->down_box(FL_ROUND_DOWN_BOX);
            radio_map_x10->labelsize(20);
          } // Fl_Round_Button* radio_map_x10
          o->end();
        } // Fl_Group* o
        tab_map_settings->end();
      } // Fl_Group* tab_map_settings
      { tab_quick_shifter = new Fl_Group(0, 60, 1280, 660, "&Quick Shifter       ");
        tab_quick_shifter->labelsize(20);
        tab_quick_shifter->hide();
        { vs_qs_enable_rpm = new Fl_Value_Slider(40, 140, 600, 50, "Enable point(r.p.m.x100)");
          vs_qs_enable_rpm->type(5);
          vs_qs_enable_rpm->color((Fl_Color)55);
          vs_qs_enable_rpm->selection_color((Fl_Color)1);
          vs_qs_enable_rpm->labelsize(24);
          vs_qs_enable_rpm->minimum(40);
          vs_qs_enable_rpm->maximum(155);
          vs_qs_enable_rpm->step(5);
          vs_qs_enable_rpm->value(120);
          vs_qs_enable_rpm->textsize(18);
          vs_qs_enable_rpm->callback((Fl_Callback*)cb_option_setting_vs);
          vs_qs_enable_rpm->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Value_Slider* vs_qs_enable_rpm
        { vs_qs_sw_on_count = new Fl_Value_Slider(40, 340, 600, 50, "Delay count  to activation(pick-up count)");
          vs_qs_sw_on_count->type(5);
          vs_qs_sw_on_count->color((Fl_Color)55);
          vs_qs_sw_on_count->selection_color((Fl_Color)1);
          vs_qs_sw_on_count->labelsize(24);
          vs_qs_sw_on_count->maximum(10);
          vs_qs_sw_on_count->step(1);
          vs_qs_sw_on_count->value(1);
          vs_qs_sw_on_count->textsize(18);
          vs_qs_sw_on_count->callback((Fl_Callback*)cb_option_setting_vs);
          vs_qs_sw_on_count->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Value_Slider* vs_qs_sw_on_count
        { vs_qs_cut_count = new Fl_Value_Slider(40, 240, 600, 50, "Count of ignition cuts(pick-up count)");
          vs_qs_cut_count->type(5);
          vs_qs_cut_count->color((Fl_Color)55);
          vs_qs_cut_count->selection_color((Fl_Color)1);
          vs_qs_cut_count->labelsize(24);
          vs_qs_cut_count->minimum(1);
          vs_qs_cut_count->maximum(50);
          vs_qs_cut_count->step(1);
          vs_qs_cut_count->value(22);
          vs_qs_cut_count->textsize(18);
          vs_qs_cut_count->callback((Fl_Callback*)cb_option_setting_vs);
          vs_qs_cut_count->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Value_Slider* vs_qs_cut_count
        { vs_qs_disable_count = new Fl_Value_Slider(40, 440, 600, 50, "Count of Invalid after activation(pick-up count)");
          vs_qs_disable_count->type(5);
          vs_qs_disable_count->color((Fl_Color)55);
          vs_qs_disable_count->selection_color((Fl_Color)1);
          vs_qs_disable_count->labelsize(24);
          vs_qs_disable_count->minimum(50);
          vs_qs_disable_count->maximum(200);
          vs_qs_disable_count->step(5);
          vs_qs_disable_count->value(100);
          vs_qs_disable_count->textsize(18);
          vs_qs_disable_count->callback((Fl_Callback*)cb_option_setting_vs);
          vs_qs_disable_count->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Value_Slider* vs_qs_disable_count
        { btn_qs_reverse_onoff_state = new Fl_Light_Button(410, 520, 227, 60, "Reverse on/off state");
          btn_qs_reverse_onoff_state->selection_color((Fl_Color)2);
          btn_qs_reverse_onoff_state->labelsize(18);
          btn_qs_reverse_onoff_state->callback((Fl_Callback*)cb_option_setting_btn);
        } // Fl_Light_Button* btn_qs_reverse_onoff_state
        { btn_qs_use_as_stopsw = new Fl_Light_Button(410, 610, 227, 60, "Use as stop switch");
          btn_qs_use_as_stopsw->selection_color((Fl_Color)2);
          btn_qs_use_as_stopsw->labelsize(18);
          btn_qs_use_as_stopsw->callback((Fl_Callback*)cb_option_setting_btn);
        } // Fl_Light_Button* btn_qs_use_as_stopsw
        { Fl_Box* o = new Fl_Box(660, 110, 600, 80, "Set the minimum engine speed (RPM) at which the quickshifter switch becomes a\
ctive. Using the quickshifter at low RPM is not recommended. The default value\
 is 70.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(660, 310, 590, 80, "Set the number of crankshaft revolutions that must occur after the quick shif\
ter switch is activated before the ignition cut engages. The default value is \
zero.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(660, 210, 580, 80, "Set the duration of the ignition cut. The default value is 11 for single-cyli\
nder engines and 22 for twin-cylinder engines.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(660, 410, 590, 80, "Set the engine speed threshold to inhibit the quick shifter switch from re-en\
gaging after the ignition cut period has ended.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(660, 500, 590, 80, "Inverts the quickshifter switch setting (ON/OFF). Please configure this accor\
ding to the switch specifications. The default setting is OFF.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(660, 590, 590, 80, "Turn this on when using the quick-shifter switch as a STOP switch. It is not \
normally used. The default setting is OFF.");
          o->labelsize(18);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        tab_quick_shifter->end();
      } // Fl_Group* tab_quick_shifter
      { tab_option_settings = new Fl_Group(0, 60, 1280, 660, "&Option Settings       ");
        tab_option_settings->labelsize(20);
        { vs_rev_limit = new Fl_Value_Slider(30, 100, 600, 50, "Rev limitter(r.p.m.x100)");
          vs_rev_limit->type(5);
          vs_rev_limit->color(FL_BACKGROUND2_COLOR);
          vs_rev_limit->selection_color((Fl_Color)1);
          vs_rev_limit->labelsize(24);
          vs_rev_limit->minimum(40);
          vs_rev_limit->maximum(160);
          vs_rev_limit->step(5);
          vs_rev_limit->value(120);
          vs_rev_limit->textsize(18);
          vs_rev_limit->callback((Fl_Callback*)cb_option_setting_vs);
          vs_rev_limit->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Value_Slider* vs_rev_limit
        { Fl_Group* o = new Fl_Group(30, 460, 600, 60, "C2 Option port");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { radio_optc2_pulse_out = new Fl_Round_Button(60, 485, 25, 25, "Ignition pulse out");
            radio_optc2_pulse_out->type(102);
            radio_optc2_pulse_out->down_box(FL_ROUND_DOWN_BOX);
            radio_optc2_pulse_out->value(1);
            radio_optc2_pulse_out->labelsize(24);
            radio_optc2_pulse_out->callback((Fl_Callback*)cb_optport_type);
          } // Fl_Round_Button* radio_optc2_pulse_out
          { radio_optc2_map_out = new Fl_Round_Button(320, 485, 25, 25, "Map switch status out");
            radio_optc2_map_out->type(102);
            radio_optc2_map_out->down_box(FL_ROUND_DOWN_BOX);
            radio_optc2_map_out->labelsize(24);
            radio_optc2_map_out->callback((Fl_Callback*)cb_optport_type);
          } // Fl_Round_Button* radio_optc2_map_out
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(650, 96, 600, 156, "Map switch type");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { radio_opt_mapsw_type1 = new Fl_Round_Button(720, 106, 25, 30, "1CH: No map switch");
            radio_opt_mapsw_type1->type(102);
            radio_opt_mapsw_type1->down_box(FL_ROUND_DOWN_BOX);
            radio_opt_mapsw_type1->value(1);
            radio_opt_mapsw_type1->labelsize(24);
            radio_opt_mapsw_type1->callback((Fl_Callback*)cb_opt_mapsw_type);
          } // Fl_Round_Button* radio_opt_mapsw_type1
          { radio_opt_mapsw_type2 = new Fl_Round_Button(720, 160, 25, 30, "2CH: On-Off map switch");
            radio_opt_mapsw_type2->type(102);
            radio_opt_mapsw_type2->down_box(FL_ROUND_DOWN_BOX);
            radio_opt_mapsw_type2->labelsize(24);
            radio_opt_mapsw_type2->callback((Fl_Callback*)cb_opt_mapsw_type);
          } // Fl_Round_Button* radio_opt_mapsw_type2
          { radio_opt_mapsw_type4 = new Fl_Round_Button(720, 212, 25, 30, "4CH: Throttle map switch");
            radio_opt_mapsw_type4->type(102);
            radio_opt_mapsw_type4->down_box(FL_ROUND_DOWN_BOX);
            radio_opt_mapsw_type4->labelsize(24);
            radio_opt_mapsw_type4->callback((Fl_Callback*)cb_opt_mapsw_type);
          } // Fl_Round_Button* radio_opt_mapsw_type4
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(30, 211, 600, 199, "Analog ignition");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { vs_count_of_an_ignition = new Fl_Value_Slider(70, 251, 550, 50, "Count of initial analog ignition");
            vs_count_of_an_ignition->type(5);
            vs_count_of_an_ignition->color((Fl_Color)55);
            vs_count_of_an_ignition->selection_color((Fl_Color)1);
            vs_count_of_an_ignition->labelsize(24);
            vs_count_of_an_ignition->maximum(60);
            vs_count_of_an_ignition->step(1);
            vs_count_of_an_ignition->value(10);
            vs_count_of_an_ignition->textsize(18);
            vs_count_of_an_ignition->callback((Fl_Callback*)cb_option_setting_vs);
            vs_count_of_an_ignition->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Value_Slider* vs_count_of_an_ignition
          { vs_rpm_for_an_ignition = new Fl_Value_Slider(70, 341, 550, 50, "Upper limit for analog ignition (r.p.m.x100)");
            vs_rpm_for_an_ignition->type(5);
            vs_rpm_for_an_ignition->color((Fl_Color)55);
            vs_rpm_for_an_ignition->selection_color((Fl_Color)1);
            vs_rpm_for_an_ignition->labelsize(24);
            vs_rpm_for_an_ignition->maximum(30);
            vs_rpm_for_an_ignition->step(1);
            vs_rpm_for_an_ignition->textsize(18);
            vs_rpm_for_an_ignition->callback((Fl_Callback*)cb_option_setting_vs);
            vs_rpm_for_an_ignition->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Value_Slider* vs_rpm_for_an_ignition
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(650, 302, 600, 328, "4ch map setting");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { vs_throttle_1to2 = new Fl_Value_Slider(670, 379, 560, 50, "Throttle map branch point: MAP 1 to 2");
            vs_throttle_1to2->type(5);
            vs_throttle_1to2->color((Fl_Color)55);
            vs_throttle_1to2->selection_color((Fl_Color)1);
            vs_throttle_1to2->labelsize(24);
            vs_throttle_1to2->maximum(255);
            vs_throttle_1to2->step(1);
            vs_throttle_1to2->value(64);
            vs_throttle_1to2->textsize(18);
            vs_throttle_1to2->callback((Fl_Callback*)cb_opt_setting_throttle);
            vs_throttle_1to2->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Value_Slider* vs_throttle_1to2
          { vs_throttle_2to3 = new Fl_Value_Slider(670, 469, 560, 50, "Throttle map branch point: MAP 2 to 3");
            vs_throttle_2to3->type(5);
            vs_throttle_2to3->color((Fl_Color)55);
            vs_throttle_2to3->selection_color((Fl_Color)1);
            vs_throttle_2to3->labelsize(24);
            vs_throttle_2to3->maximum(255);
            vs_throttle_2to3->step(1);
            vs_throttle_2to3->value(128);
            vs_throttle_2to3->textsize(18);
            vs_throttle_2to3->callback((Fl_Callback*)cb_opt_setting_throttle);
            vs_throttle_2to3->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Value_Slider* vs_throttle_2to3
          { vs_throttle_3to4 = new Fl_Value_Slider(670, 560, 560, 50, "Throttle map branch point: MAP 3 to 4");
            vs_throttle_3to4->type(5);
            vs_throttle_3to4->color((Fl_Color)55);
            vs_throttle_3to4->selection_color((Fl_Color)1);
            vs_throttle_3to4->labelsize(24);
            vs_throttle_3to4->maximum(255);
            vs_throttle_3to4->step(1);
            vs_throttle_3to4->value(192);
            vs_throttle_3to4->textsize(18);
            vs_throttle_3to4->callback((Fl_Callback*)cb_opt_setting_throttle);
            vs_throttle_3to4->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          } // Fl_Value_Slider* vs_throttle_3to4
          { pr_tp_current = new Fl_Progress(700, 314, 525, 25, "CURRENT VALUE");
            pr_tp_current->selection_color(FL_DARK_GREEN);
          } // Fl_Progress* pr_tp_current
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(30, 570, 600, 60, "PV Initial mode ");
          o->box(FL_BORDER_FRAME);
          o->color(FL_INACTIVE_COLOR);
          o->labelsize(24);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          { radio_opt_pv_init_open_end = new Fl_Round_Button(60, 595, 25, 25, "Full open end");
            radio_opt_pv_init_open_end->type(102);
            radio_opt_pv_init_open_end->down_box(FL_ROUND_DOWN_BOX);
            radio_opt_pv_init_open_end->value(1);
            radio_opt_pv_init_open_end->labelsize(24);
            radio_opt_pv_init_open_end->callback((Fl_Callback*)cb_pviinit_type);
          } // Fl_Round_Button* radio_opt_pv_init_open_end
          { radio_opt_pv_init_close_end = new Fl_Round_Button(320, 595, 25, 25, "Full close end");
            radio_opt_pv_init_close_end->type(102);
            radio_opt_pv_init_close_end->down_box(FL_ROUND_DOWN_BOX);
            radio_opt_pv_init_close_end->labelsize(24);
            radio_opt_pv_init_close_end->callback((Fl_Callback*)cb_pviinit_type);
          } // Fl_Round_Button* radio_opt_pv_init_close_end
          o->end();
        } // Fl_Group* o
        tab_option_settings->end();
      } // Fl_Group* tab_option_settings
      { Fl_Group* o = new Fl_Group(0, 60, 1280, 660, "    About    ");
        o->labelsize(20);
        o->hide();
        { Fl_Box* o = new Fl_Box(20, 80, 1230, 630, "/* --------------------------------------------------------------------------\
--\nOpen Source Replica CDI \'OSR-CDI\' system for YAMAHA 2T motorcycle\n-----\
-----------------------------------------------------------------------\nCopyr\
ight(c) 2013 - 2026 Rilassaru(http://rilassaru.blog.jp/)\nAll rights reserved.\
\n\nRedistribution and use in source and binary forms, with or without\nmodifi\
cation, are permitted provided that the following conditions are met :\n\n1. R\
edistributions of source code must retain the above copyright notice,\nthis li\
st of conditions and the following disclaimer.\n2. Redistributions in binary f\
orm must reproduce the above copyright notice,\nthis list of conditions and th\
e following disclaimer in the documentation\nand / or other materials provided\
 with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS \
AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, \
BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR\
 A PARTICULAR PURPOSE ARE\nDISCLAIMED.IN NO EVENT SHALL THE COPYRIGHT OWNER OR\
 CONTRIBUTORS BE LIABLE FOR\nANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPL\
ARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF \
SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTE\
RRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\
 STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY\
 WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF S\
UCH DAMAGE.\n\nThe views and conclusions contained in the software and documen\
tation are those\nof the authors and should not be interpreted as representing\
 official policies,\neither expressed or implied, of the FreeBSD Project.\n---\
-------------------------------------------------------------------------*/");
          o->labelfont(4);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Box* o
        o->end();
      } // Fl_Group* o
      tabs_window->end();
    } // Fl_Tabs* tabs_window
    o->end();
    o->resizable(o);
  } // Fl_Double_Window* o
  return w;
}
