// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef flscreen_h
#define flscreen_h
#include <FL/Fl.H>
#include "mymsg.h"
#include "MyChart.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs_window;
#include <FL/Fl_Group.H>
extern Fl_Group *tab_device_infomation;
#include <FL/Fl_Box.H>
#include <FL/Fl_Round_Button.H>
extern void cb_engine_type(Fl_Round_Button*, void*);
extern Fl_Round_Button *radio_single_pulse;
extern Fl_Round_Button *radio_twin_pulse;
#include <FL/Fl_Int_Input.H>
extern void cb_sys_pickup_degree(Fl_Int_Input*, void*);
extern Fl_Int_Input *sys_pickup_degree;
extern MyMsg *msg;
#include <FL/Fl_Output.H>
extern Fl_Output *dev_manufacture;
extern Fl_Output *dev_product;
extern Fl_Output *dev_mapsw;
extern Fl_Output *dev_quickshifter;
extern Fl_Output *dev_rpm;
extern Fl_Output *dev_pv_pot;
extern Fl_Output *dev_devid;
extern Fl_Output *dev_revid;
extern Fl_Output *dev_pv_target;
extern Fl_Output *dev_pv_mode;
extern Fl_Output *dev_pv_mt_state;
#include <FL/Fl_Button.H>
extern void cb_device_read(Fl_Button*, void*);
extern Fl_Button *btn_dev_read;
extern void cb_device_write(Fl_Button*, void*);
extern Fl_Button *btn_dev_write;
extern void cb_file_open(Fl_Button*, void*);
extern Fl_Button *btn_file_open;
extern void cb_file_save(Fl_Button*, void*);
extern Fl_Button *btn_file_save;
extern Fl_Output *dev_th_pot;
#include <FL/Fl_Progress.H>
extern Fl_Progress *pr_cputemp_current;
extern Fl_Group *tab_map_settings;
extern MyChart *chart_ign;
extern MyChart *chart_pvs;
#include <FL/Fl_Repeat_Button.H>
extern void cb_up(Fl_Repeat_Button*, void*);
extern Fl_Repeat_Button *btn_map_up;
extern void cb_down(Fl_Repeat_Button*, void*);
extern Fl_Repeat_Button *btn_map_down;
extern void cb_left(Fl_Repeat_Button*, void*);
extern Fl_Repeat_Button *btn_map_left;
extern void cb_right(Fl_Repeat_Button*, void*);
extern Fl_Repeat_Button *btn_map_right;
#include <FL/Fl_Light_Button.H>
extern void cb_select_map(Fl_Light_Button*, void*);
extern Fl_Light_Button *btn_select_ign_map0;
extern Fl_Light_Button *btn_select_ign_map1;
extern Fl_Light_Button *btn_select_ign_map2;
extern Fl_Light_Button *btn_select_ign_map3;
extern Fl_Light_Button *btn_select_pvs_map0;
extern Fl_Light_Button *btn_select_pvs_map1;
extern Fl_Light_Button *btn_select_pvs_map2;
extern Fl_Light_Button *btn_select_pvs_map3;
extern Fl_Round_Button *radio_map_x1;
extern Fl_Round_Button *radio_map_x5;
extern Fl_Round_Button *radio_map_x10;
extern Fl_Group *tab_quick_shifter;
#include <FL/Fl_Value_Slider.H>
extern void cb_option_setting_vs(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *vs_qs_enable_rpm;
extern Fl_Value_Slider *vs_qs_sw_on_count;
extern Fl_Value_Slider *vs_qs_cut_count;
extern Fl_Value_Slider *vs_qs_disable_count;
extern void cb_option_setting_btn(Fl_Light_Button*, void*);
extern Fl_Light_Button *btn_qs_reverse_onoff_state;
extern Fl_Light_Button *btn_qs_use_as_stopsw;
extern Fl_Group *tab_option_settings;
extern Fl_Value_Slider *vs_rev_limit;
extern void cb_optport_type(Fl_Round_Button*, void*);
extern Fl_Round_Button *radio_optc2_pulse_out;
extern Fl_Round_Button *radio_optc2_map_out;
extern void cb_opt_mapsw_type(Fl_Round_Button*, void*);
extern Fl_Round_Button *radio_opt_mapsw_type1;
extern Fl_Round_Button *radio_opt_mapsw_type2;
extern Fl_Round_Button *radio_opt_mapsw_type4;
extern Fl_Value_Slider *vs_count_of_an_ignition;
extern Fl_Value_Slider *vs_rpm_for_an_ignition;
extern void cb_opt_setting_throttle(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *vs_throttle_1to2;
extern Fl_Value_Slider *vs_throttle_2to3;
extern Fl_Value_Slider *vs_throttle_3to4;
extern Fl_Progress *pr_tp_current;
extern void cb_pviinit_type(Fl_Round_Button*, void*);
extern Fl_Round_Button *radio_opt_pv_init_open_end;
extern Fl_Round_Button *radio_opt_pv_init_close_end;
Fl_Double_Window* make_window();
#endif
